cc_library(
    name = "log",
    hdrs = [
        "log.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "mylog",
    hdrs = [
        "mylog.h",
    ],
    visibility = ["//visibility:public"],
)